# k8sutils.yaml
apiVersion: v1
kind: Pod
metadata:
  name: k8sutils
  namespace: kubernetes-bible
spec:
  containers:
    - name: k8sutils
      image: quay.io/iamgini/k8sutils:debian12
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 200Mi
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "infinity"
      # imagePullPolicy: IfNotPresent
  restartPolicy: Always
