# immutable-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: immutable-configmap
  namespace: kubernetes-bible
data:
  color: "blue"
  version: "1.0"
  environment: "prod"
immutable: true
