# multi-container-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: kubernetes-bible

spec:
  restartPolicy: Never
  containers:
    - name: nginx-container
      image: nginx:1.29.6
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 200Mi
      imagePullPolicy: IfNotPresent
    - name: debian-container
      image: debian:13.4-slim
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 300Mi
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c", "while true; do date;echo debian-container; sleep 5 ; done"]
